name: with_it
description: with_it
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_core: 2.27.1
  firebase_messaging: 14.7.20
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  protobuf: ^3.1.0
  rinf: 4.20.0
  rxdart: ^0.27.7
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.otf
          weight: 100
        - asset: assets/font/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/font/Pretendard-Light.otf
          weight: 300
        - asset: assets/font/Pretendard-Regular.otf
          weight: 400
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/Pretendard-Black.otf
          weight: 900
